version: '3'


service: 
  postgres:
    image: postgres:latest
    container_name: postgres-api
    ports:
    - "5432:5432"
    enviroment:
      POSTGRES_PASSWORD: 1234
    volumes: 
    - ./data:/var/lib/postgresql/data